import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { hashPassword } from "./auth";
import { ApiError } from "./api-utils";
import { riskLevelFromPercent } from "@/lib/risk";
import type { QuizAttempt, QuizQuestion, RiskLevel, User } from "@/lib/types";

// A row as stored in the `users` table — has the password hash the API
// layer must never send to the client.
export interface UserRow extends User {
  passwordHash: string;
  tokenVersion: number;
  referredBy: string | null;
}

const DATA_DIR = path.join(process.cwd(), "data");
const DB_PATH = path.join(DATA_DIR, "mammoai.db");

declare global {
  var __mammoaiDb: Database.Database | undefined;
}

function openDb(): Database.Database {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  const db = new Database(DB_PATH);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  // Let a second concurrent process (e.g. a build tool evaluating several
  // route modules in parallel) wait for the writer lock instead of failing
  // outright — paired with the .immediate() seed transaction below.
  db.pragma("busy_timeout = 5000");
  return db;
}

// Reused across hot-reloads in dev (Next.js re-evaluates modules per
// request in some modes) so we don't open the file dozens of times.
const db = global.__mammoaiDb ?? openDb();
if (process.env.NODE_ENV !== "production") global.__mammoaiDb = db;

db.exec(`
  -- Small key/value store for admin-configurable settings (Telegram bot
  -- token, etc.) — lets the admin panel manage these instead of editing
  -- env vars on the server.
  CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
  );

  CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    passport_series TEXT NOT NULL,
    phone TEXT DEFAULT '',
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS quiz_questions (
    id TEXT PRIMARY KEY,
    "order" INTEGER NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    text TEXT NOT NULL,
    options TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS quiz_attempts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    answers TEXT NOT NULL,
    total_score INTEGER NOT NULL,
    max_score INTEGER NOT NULL,
    percent INTEGER NOT NULL,
    risk_level TEXT NOT NULL,
    created_at TEXT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_attempts_user ON quiz_attempts(user_id);

  -- Failed/attempted auth actions, keyed by an arbitrary identifier
  -- (ip:1.2.3.4, email:someone@x.com, ...) for simple sliding-window rate
  -- limiting — see isRateLimited() below.
  CREATE TABLE IF NOT EXISTS auth_attempts (
    id TEXT PRIMARY KEY,
    identifier TEXT NOT NULL,
    created_at TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_auth_attempts_identifier ON auth_attempts(identifier, created_at);

  -- Free-form feedback submitted from the site or the Telegram bot.
  -- user_id is nullable so a user can be deleted (bot self-service delete)
  -- without losing the feedback trail — it just becomes unattributed.
  CREATE TABLE IF NOT EXISTS feedback (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    message TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'site',
    created_at TEXT NOT NULL
  );

  -- Short-lived one-time codes for "log in to the site from Telegram"
  -- (generated by the bot, typed into the login page). Expires quickly —
  -- see consumeTelegramLoginCode().
  CREATE TABLE IF NOT EXISTS telegram_login_codes (
    code TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL
  );
`);

// Small forward-compatible migration: add columns that didn't exist in
// earlier versions of this schema, without disturbing existing data.
function ensureColumn(table: string, column: string, ddl: string) {
  const cols = db.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[];
  if (!cols.some((c) => c.name === column)) {
    db.exec(`ALTER TABLE ${table} ADD COLUMN ${ddl}`);
  }
}
ensureColumn("users", "telegram_chat_id", "telegram_chat_id TEXT");
ensureColumn("users", "telegram_link_token", "telegram_link_token TEXT");
ensureColumn("users", "last_reminder_sent_at", "last_reminder_sent_at TEXT");
// Tracks the site-independent monthly self-exam nudge the Telegram bot sends
// (separate cadence from the 90-day retest reminder above) — see
// scripts/telegram-bot.mjs, the only writer/reader of this column.
ensureColumn("users", "last_self_exam_reminder_sent_at", "last_self_exam_reminder_sent_at TEXT");
// Optional per-question uz/ru/en overrides — see QuizQuestion["translations"].
// Null/absent means "no translation entered yet", callers fall back to the
// base (admin-authored) text/options.
ensureColumn("quiz_questions", "translations", "translations TEXT");
// Bumped by "log out of all devices" — see bumpTokenVersion(). Baked into
// every JWT at sign time (see server/auth.ts); a mismatch means the token
// predates the bump and is rejected.
ensureColumn("users", "token_version", "token_version INTEGER NOT NULL DEFAULT 0");
// Referral program: each user gets a stable short code (backfilled below for
// pre-existing rows), and we remember who referred whom.
ensureColumn("users", "referral_code", "referral_code TEXT");
ensureColumn("users", "referred_by", "referred_by TEXT REFERENCES users(id) ON DELETE SET NULL");

db.exec(`
  -- Admin action history (who deleted/changed what, and when) — read-only
  -- from the UI, useful once there's more than one admin/moderator account.
  CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    admin_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    admin_name TEXT NOT NULL,
    action TEXT NOT NULL,
    target TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at);

  -- One row per (user, calendar month) a self-exam was marked done — the
  -- site's equivalent of the bot's monthly self-exam reminder, but
  -- self-reported instead of nudged.
  CREATE TABLE IF NOT EXISTS self_exam_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(user_id, month)
  );

  -- Lightweight tracked profiles (not full accounts) an account holder can
  -- take the test "on behalf of" — e.g. a mother tracking her own mother's
  -- or sister's risk alongside her own.
  CREATE TABLE IF NOT EXISTS family_members (
    id TEXT PRIMARY KEY,
    owner_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL DEFAULT '',
    relation TEXT NOT NULL DEFAULT '',
    birth_date TEXT,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS faq_items (
    id TEXT PRIMARY KEY,
    "order" INTEGER NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    translations TEXT,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS clinics (
    id TEXT PRIMARY KEY,
    "order" INTEGER NOT NULL,
    name TEXT NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS articles (
    id TEXT PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL,
    published INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  );

  -- Web Push subscriptions (browser notifications) — one row per
  -- browser/device a user has enabled notifications on. Consumed by
  -- scripts/push-reminders.mjs, the browser-notification equivalent of the
  -- Telegram bot's reminder loop.
  CREATE TABLE IF NOT EXISTS push_subscriptions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint TEXT UNIQUE NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_reminder_sent_at TEXT,
    last_self_exam_sent_at TEXT
  );
`);

// Backfill a referral code for any user created before this feature existed.
{
  const missing = db.prepare("SELECT id FROM users WHERE referral_code IS NULL").all() as { id: string }[];
  const setCode = db.prepare("UPDATE users SET referral_code = ? WHERE id = ?");
  for (const { id } of missing) setCode.run(randomUUID().slice(0, 8), id);
}

// Which family member (if any) a quiz attempt was taken on behalf of — null
// means "the account holder took it themselves", same as before this column
// existed. Added after the family_members table above so the FK target exists.
ensureColumn(
  "quiz_attempts",
  "family_member_id",
  "family_member_id TEXT REFERENCES family_members(id) ON DELETE SET NULL"
);
// An article with a video_url is shown as a "video lesson" — same content
// type, just optionally fronted by an embedded video (see youtubeEmbedUrl
// on the qo'llanma page for the same embedding logic).
ensureColumn("articles", "video_url", "video_url TEXT");

// ---------------------------------------------------------------------------
// Row <-> domain-type mapping
// ---------------------------------------------------------------------------

function rowToUser(row: {
  id: string;
  email: string;
  password_hash: string;
  role: string;
  first_name: string;
  last_name: string;
  birth_date: string;
  passport_series: string;
  phone: string | null;
  created_at: string;
  token_version: number;
  referral_code: string | null;
  referred_by: string | null;
}): UserRow {
  return {
    id: row.id,
    email: row.email,
    passwordHash: row.password_hash,
    role: row.role as User["role"],
    firstName: row.first_name,
    lastName: row.last_name,
    birthDate: row.birth_date,
    passportSeries: row.passport_series,
    phone: row.phone ?? "",
    createdAt: row.created_at,
    tokenVersion: row.token_version ?? 0,
    referralCode: row.referral_code ?? "",
    referredBy: row.referred_by,
  };
}

export function toPublicUser(row: UserRow): User {
  return {
    id: row.id,
    email: row.email,
    role: row.role,
    firstName: row.firstName,
    lastName: row.lastName,
    birthDate: row.birthDate,
    passportSeries: row.passportSeries,
    phone: row.phone,
    createdAt: row.createdAt,
    referralCode: row.referralCode,
  };
}

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export function getUserByEmail(email: string): UserRow | undefined {
  const row = db
    .prepare("SELECT * FROM users WHERE lower(email) = lower(?)")
    .get(email) as Parameters<typeof rowToUser>[0] | undefined;
  return row ? rowToUser(row) : undefined;
}

export function getUserById(id: string): UserRow | undefined {
  const row = db.prepare("SELECT * FROM users WHERE id = ?").get(id) as
    | Parameters<typeof rowToUser>[0]
    | undefined;
  return row ? rowToUser(row) : undefined;
}

export function getAllUsers(): UserRow[] {
  const rows = db.prepare("SELECT * FROM users ORDER BY created_at ASC").all() as Parameters<
    typeof rowToUser
  >[0][];
  return rows.map(rowToUser);
}

export function createUser(input: {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  birthDate: string;
  passportSeries: string;
  phone?: string;
  role?: "user" | "admin" | "moderator";
  referredByCode?: string;
}): UserRow {
  if (getUserByEmail(input.email)) {
    throw new ApiError(409, "Bu email allaqachon ro'yxatdan o'tgan.");
  }
  const referrer = input.referredByCode ? getUserByReferralCode(input.referredByCode) : undefined;
  const row: UserRow = {
    id: randomUUID(),
    email: input.email,
    passwordHash: hashPassword(input.password),
    role: input.role ?? "user",
    firstName: input.firstName,
    lastName: input.lastName,
    birthDate: input.birthDate,
    passportSeries: input.passportSeries,
    phone: input.phone ?? "",
    createdAt: new Date().toISOString(),
    tokenVersion: 0,
    referralCode: randomUUID().slice(0, 8),
    referredBy: referrer?.id ?? null,
  };
  db.prepare(
    `INSERT INTO users (id, email, password_hash, role, first_name, last_name, birth_date, passport_series, phone, created_at, token_version, referral_code, referred_by)
     VALUES (@id, @email, @passwordHash, @role, @firstName, @lastName, @birthDate, @passportSeries, @phone, @createdAt, @tokenVersion, @referralCode, @referredBy)`
  ).run(row);
  return row;
}

export function getUserByReferralCode(code: string): UserRow | undefined {
  const row = db.prepare("SELECT * FROM users WHERE referral_code = ?").get(code) as
    | Parameters<typeof rowToUser>[0]
    | undefined;
  return row ? rowToUser(row) : undefined;
}

/** Count of accounts referred by this user — shown on their profile. */
export function getReferralCount(userId: string): number {
  const { n } = db.prepare("SELECT COUNT(*) AS n FROM users WHERE referred_by = ?").get(userId) as { n: number };
  return n;
}

/** "Log out of all devices": every previously issued token stops verifying. */
export function bumpTokenVersion(userId: string): number {
  db.prepare("UPDATE users SET token_version = token_version + 1 WHERE id = ?").run(userId);
  return (db.prepare("SELECT token_version FROM users WHERE id = ?").get(userId) as { token_version: number })
    .token_version;
}

export function updateUserProfile(
  id: string,
  patch: Partial<Pick<User, "firstName" | "lastName" | "birthDate" | "passportSeries" | "phone">>
): UserRow | undefined {
  const current = getUserById(id);
  if (!current) return undefined;
  const next = { ...current, ...patch };
  db.prepare(
    `UPDATE users SET first_name=@firstName, last_name=@lastName, birth_date=@birthDate,
     passport_series=@passportSeries, phone=@phone WHERE id=@id`
  ).run(next);
  return next;
}

export function deleteUser(id: string) {
  db.prepare("DELETE FROM users WHERE id = ?").run(id);
}

export function setUserRole(id: string, role: "user" | "moderator"): UserRow {
  db.prepare("UPDATE users SET role = ? WHERE id = ?").run(role, id);
  return getUserById(id)!;
}

export function updateUserPasswordHash(id: string, passwordHash: string) {
  db.prepare("UPDATE users SET password_hash = ? WHERE id = ?").run(passwordHash, id);
}

/**
 * Identity-based password reset: since there's no outbound email set up,
 * "forgot password" verifies the same passport series + birth date collected
 * at signup instead of an emailed link. Returns the matching user or
 * undefined — callers should give a generic error either way, to avoid
 * leaking which field (if any) was wrong.
 */
export function findUserForReset(
  email: string,
  passportSeries: string,
  birthDate: string
): UserRow | undefined {
  const user = getUserByEmail(email);
  if (!user) return undefined;
  if (user.passportSeries.toUpperCase() !== passportSeries.toUpperCase()) return undefined;
  if (user.birthDate !== birthDate) return undefined;
  return user;
}

export interface UserWithLatestAttempt extends User {
  latestAttempt: { percent: number; riskLevel: RiskLevel; createdAt: string } | null;
}

export function getAllUsersWithLatestAttempt(): UserWithLatestAttempt[] {
  const rows = db
    .prepare(
      `SELECT u.*,
        (SELECT percent FROM quiz_attempts a WHERE a.user_id = u.id ORDER BY a.created_at DESC LIMIT 1) AS latest_percent,
        (SELECT risk_level FROM quiz_attempts a WHERE a.user_id = u.id ORDER BY a.created_at DESC LIMIT 1) AS latest_risk_level,
        (SELECT created_at FROM quiz_attempts a WHERE a.user_id = u.id ORDER BY a.created_at DESC LIMIT 1) AS latest_created_at
       FROM users u ORDER BY u.created_at ASC`
    )
    .all() as (Parameters<typeof rowToUser>[0] & {
    latest_percent: number | null;
    latest_risk_level: string | null;
    latest_created_at: string | null;
  })[];

  return rows.map((row) => ({
    ...toPublicUser(rowToUser(row)),
    latestAttempt:
      row.latest_percent != null
        ? {
            percent: row.latest_percent,
            riskLevel: row.latest_risk_level as RiskLevel,
            createdAt: row.latest_created_at as string,
          }
        : null,
  }));
}

// ---------------------------------------------------------------------------
// Quiz questions
// ---------------------------------------------------------------------------

function rowToQuestion(row: {
  id: string;
  order: number;
  category: string;
  text: string;
  options: string;
  translations: string | null;
}): QuizQuestion {
  return {
    id: row.id,
    order: row.order,
    category: row.category,
    text: row.text,
    options: JSON.parse(row.options),
    translations: row.translations ? JSON.parse(row.translations) : undefined,
  };
}

export function getQuestions(): QuizQuestion[] {
  const rows = db.prepare('SELECT * FROM quiz_questions ORDER BY "order" ASC').all() as Parameters<
    typeof rowToQuestion
  >[0][];
  return rows.map(rowToQuestion);
}

export function getQuestionById(id: string): QuizQuestion | undefined {
  const row = db.prepare("SELECT * FROM quiz_questions WHERE id = ?").get(id) as
    | Parameters<typeof rowToQuestion>[0]
    | undefined;
  return row ? rowToQuestion(row) : undefined;
}

export function createQuestion(input: Omit<QuizQuestion, "id">): QuizQuestion {
  const question: QuizQuestion = { ...input, id: randomUUID() };
  db.prepare(
    `INSERT INTO quiz_questions (id, "order", category, text, options, translations) VALUES (@id, @order, @category, @text, @options, @translations)`
  ).run({
    ...question,
    options: JSON.stringify(question.options),
    translations: question.translations ? JSON.stringify(question.translations) : null,
  });
  return question;
}

export function updateQuestion(id: string, input: Omit<QuizQuestion, "id">): QuizQuestion {
  const question: QuizQuestion = { ...input, id };
  db.prepare(
    `UPDATE quiz_questions SET "order"=@order, category=@category, text=@text, options=@options, translations=@translations WHERE id=@id`
  ).run({
    ...question,
    options: JSON.stringify(question.options),
    translations: question.translations ? JSON.stringify(question.translations) : null,
  });
  return question;
}

export function deleteQuestion(id: string) {
  db.prepare("DELETE FROM quiz_questions WHERE id = ?").run(id);
}

export function reorderQuestions(orderedIds: string[]) {
  const update = db.prepare('UPDATE quiz_questions SET "order" = ? WHERE id = ?');
  const tx = db.transaction((ids: string[]) => {
    ids.forEach((id, index) => update.run(index + 1, id));
  });
  tx(orderedIds);
}

// ---------------------------------------------------------------------------
// Quiz attempts
// ---------------------------------------------------------------------------

function rowToAttempt(row: {
  id: string;
  user_id: string;
  answers: string;
  total_score: number;
  max_score: number;
  percent: number;
  risk_level: string;
  created_at: string;
  first_name?: string;
  last_name?: string;
  family_member_id?: string | null;
}): QuizAttempt {
  return {
    id: row.id,
    userId: row.user_id,
    userFirstName: row.first_name,
    userLastName: row.last_name,
    familyMemberId: row.family_member_id ?? null,
    answers: JSON.parse(row.answers),
    totalScore: row.total_score,
    maxScore: row.max_score,
    percent: row.percent,
    riskLevel: row.risk_level as RiskLevel,
    createdAt: row.created_at,
  };
}

export function getAttemptsForUser(userId: string): QuizAttempt[] {
  const rows = db
    .prepare("SELECT * FROM quiz_attempts WHERE user_id = ? ORDER BY created_at DESC")
    .all(userId) as Parameters<typeof rowToAttempt>[0][];
  return rows.map(rowToAttempt);
}

export function getAllAttempts(): QuizAttempt[] {
  const rows = db
    .prepare(
      `SELECT a.*, u.first_name, u.last_name FROM quiz_attempts a
       JOIN users u ON u.id = a.user_id
       ORDER BY a.created_at DESC`
    )
    .all() as Parameters<typeof rowToAttempt>[0][];
  return rows.map(rowToAttempt);
}

/** Recomputes the score server-side from the current questions — never trusts a client-supplied score. */
export function submitAttempt(
  userId: string,
  selections: { questionId: string; optionId: string }[],
  familyMemberId?: string | null
): QuizAttempt {
  const questions = getQuestions();
  const maxScore = questions.reduce(
    (sum, q) => sum + Math.max(...q.options.map((o) => o.score), 0),
    0
  );

  const answers = selections.map((sel) => {
    const question = questions.find((q) => q.id === sel.questionId);
    const option = question?.options.find((o) => o.id === sel.optionId);
    if (!question || !option) {
      throw new Error("Noto'g'ri savol yoki javob variant tanlandi.");
    }
    return { questionId: sel.questionId, optionId: sel.optionId, score: option.score };
  });

  const totalScore = answers.reduce((sum, a) => sum + a.score, 0);
  const percent = maxScore > 0 ? Math.round((totalScore / maxScore) * 100) : 0;

  const attempt: QuizAttempt = {
    id: randomUUID(),
    userId,
    familyMemberId: familyMemberId ?? null,
    answers,
    totalScore,
    maxScore,
    percent,
    riskLevel: riskLevelFromPercent(percent),
    createdAt: new Date().toISOString(),
  };

  db.prepare(
    `INSERT INTO quiz_attempts (id, user_id, answers, total_score, max_score, percent, risk_level, created_at, family_member_id)
     VALUES (@id, @userId, @answers, @totalScore, @maxScore, @percent, @riskLevel, @createdAt, @familyMemberId)`
  ).run({ ...attempt, answers: JSON.stringify(attempt.answers) });

  return attempt;
}

// ---------------------------------------------------------------------------
// Rate limiting — simple sliding-window counter over auth_attempts.
// ---------------------------------------------------------------------------

export function recordAuthAttempt(identifier: string) {
  db.prepare("INSERT INTO auth_attempts (id, identifier, created_at) VALUES (?, ?, ?)").run(
    randomUUID(),
    identifier,
    new Date().toISOString()
  );
}

export function isRateLimited(identifier: string, maxAttempts: number, windowMs: number): boolean {
  const since = new Date(Date.now() - windowMs).toISOString();
  const { n } = db
    .prepare("SELECT COUNT(*) AS n FROM auth_attempts WHERE identifier = ? AND created_at > ?")
    .get(identifier, since) as { n: number };
  return n >= maxAttempts;
}

export function clearAuthAttempts(identifier: string) {
  db.prepare("DELETE FROM auth_attempts WHERE identifier = ?").run(identifier);
}

// Keeps the table from growing forever on a long-lived server — attempts
// older than a day are never useful for any window we use.
export function pruneOldAuthAttempts() {
  const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  db.prepare("DELETE FROM auth_attempts WHERE created_at < ?").run(cutoff);
}

// ---------------------------------------------------------------------------
// Telegram linking (used by scripts/telegram-bot.mjs, run as its own
// process — see that file for the bot/reminder loop itself)
// ---------------------------------------------------------------------------

export function setTelegramLinkToken(userId: string, token: string) {
  db.prepare("UPDATE users SET telegram_link_token = ? WHERE id = ?").run(token, userId);
}

export function getUserByTelegramLinkToken(token: string): UserRow | undefined {
  const row = db.prepare("SELECT * FROM users WHERE telegram_link_token = ?").get(token) as
    | Parameters<typeof rowToUser>[0]
    | undefined;
  return row ? rowToUser(row) : undefined;
}

export function setTelegramChatId(userId: string, chatId: string | null) {
  db.prepare("UPDATE users SET telegram_chat_id = ?, telegram_link_token = NULL WHERE id = ?").run(
    chatId,
    userId
  );
}

export function getTelegramChatId(userId: string): string | null {
  const row = db.prepare("SELECT telegram_chat_id FROM users WHERE id = ?").get(userId) as
    | { telegram_chat_id: string | null }
    | undefined;
  return row?.telegram_chat_id ?? null;
}

/** Users linked to Telegram whose latest attempt is old enough for a reminder, and who haven't been nudged recently. */
export function getUsersDueForTelegramReminder(retestDays: number, reminderCooldownDays: number) {
  const retestCutoff = new Date(Date.now() - retestDays * 24 * 60 * 60 * 1000).toISOString();
  const cooldownCutoff = new Date(Date.now() - reminderCooldownDays * 24 * 60 * 60 * 1000).toISOString();
  const rows = db
    .prepare(
      `SELECT u.id, u.first_name, u.telegram_chat_id,
        (SELECT created_at FROM quiz_attempts a WHERE a.user_id = u.id ORDER BY a.created_at DESC LIMIT 1) AS latest_at
       FROM users u
       WHERE u.telegram_chat_id IS NOT NULL
         AND (u.last_reminder_sent_at IS NULL OR u.last_reminder_sent_at < ?)`
    )
    .all(cooldownCutoff) as {
    id: string;
    first_name: string;
    telegram_chat_id: string;
    latest_at: string | null;
  }[];

  return rows.filter((r) => r.latest_at && r.latest_at < retestCutoff);
}

export function markTelegramReminderSent(userId: string) {
  db.prepare("UPDATE users SET last_reminder_sent_at = ? WHERE id = ?").run(
    new Date().toISOString(),
    userId
  );
}

/** Chat IDs of every user who has ever linked the Telegram bot — used by the admin broadcast. */
export function getAllLinkedTelegramChatIds(): string[] {
  const rows = db
    .prepare("SELECT telegram_chat_id FROM users WHERE telegram_chat_id IS NOT NULL")
    .all() as { telegram_chat_id: string }[];
  return rows.map((r) => r.telegram_chat_id);
}

/** Chat IDs of admin accounts (role='admin') that have linked Telegram — for "needs attention" alerts. */
export function getLinkedAdminTelegramChatIds(): string[] {
  const rows = db
    .prepare("SELECT telegram_chat_id FROM users WHERE role = 'admin' AND telegram_chat_id IS NOT NULL")
    .all() as { telegram_chat_id: string }[];
  return rows.map((r) => r.telegram_chat_id);
}

// ---------------------------------------------------------------------------
// Telegram "log in to the site" codes — generated by the bot, consumed once
// by /api/auth/telegram-login.
// ---------------------------------------------------------------------------

const TELEGRAM_LOGIN_CODE_TTL_MS = 10 * 60 * 1000; // 10 minutes

export function createTelegramLoginCode(userId: string): string {
  db.prepare("DELETE FROM telegram_login_codes WHERE expires_at < ?").run(new Date().toISOString());
  const code = String(Math.floor(100000 + Math.random() * 900000)); // 6 digits
  const expiresAt = new Date(Date.now() + TELEGRAM_LOGIN_CODE_TTL_MS).toISOString();
  db.prepare("INSERT OR REPLACE INTO telegram_login_codes (code, user_id, expires_at) VALUES (?, ?, ?)").run(
    code,
    userId,
    expiresAt
  );
  return code;
}

/** Looks up + deletes a login code (one-time use). Returns the matching user, or undefined if invalid/expired. */
export function consumeTelegramLoginCode(code: string): UserRow | undefined {
  const row = db.prepare("SELECT user_id, expires_at FROM telegram_login_codes WHERE code = ?").get(code) as
    | { user_id: string; expires_at: string }
    | undefined;
  if (!row) return undefined;
  db.prepare("DELETE FROM telegram_login_codes WHERE code = ?").run(code);
  if (row.expires_at < new Date().toISOString()) return undefined;
  return getUserById(row.user_id);
}

// ---------------------------------------------------------------------------
// Feedback (site + Telegram bot)
// ---------------------------------------------------------------------------

export interface FeedbackRow {
  id: string;
  userId: string | null;
  userFirstName: string | null;
  userLastName: string | null;
  userEmail: string | null;
  message: string;
  source: string;
  createdAt: string;
}

export function createFeedback(userId: string | null, message: string, source: "site" | "bot") {
  db.prepare("INSERT INTO feedback (id, user_id, message, source, created_at) VALUES (?, ?, ?, ?, ?)").run(
    randomUUID(),
    userId,
    message,
    source,
    new Date().toISOString()
  );
}

export function getAllFeedback(): FeedbackRow[] {
  const rows = db
    .prepare(
      `SELECT f.id, f.user_id, f.message, f.source, f.created_at, u.first_name, u.last_name, u.email
       FROM feedback f LEFT JOIN users u ON u.id = f.user_id
       ORDER BY f.created_at DESC`
    )
    .all() as {
    id: string;
    user_id: string | null;
    message: string;
    source: string;
    created_at: string;
    first_name: string | null;
    last_name: string | null;
    email: string | null;
  }[];
  return rows.map((r) => ({
    id: r.id,
    userId: r.user_id,
    userFirstName: r.first_name,
    userLastName: r.last_name,
    userEmail: r.email,
    message: r.message,
    source: r.source,
    createdAt: r.created_at,
  }));
}

export function deleteFeedback(id: string) {
  db.prepare("DELETE FROM feedback WHERE id = ?").run(id);
}

// ---------------------------------------------------------------------------
// Admin dashboard trend data — new signups and quiz attempts per day, for
// the last N days (oldest first). Days with zero of either are included
// with a 0 count, so the chart's x-axis has no gaps.
// ---------------------------------------------------------------------------

export interface DailyCounts {
  date: string; // YYYY-MM-DD
  signups: number;
  attempts: number;
}

/** Aggregate-only counts safe to show on the public landing page. */
export function getPublicCommunityStats(): { totalUsers: number; totalAttempts: number } {
  const totalUsers = (db.prepare("SELECT COUNT(*) AS n FROM users WHERE role = 'user'").get() as { n: number }).n;
  const totalAttempts = (db.prepare("SELECT COUNT(*) AS n FROM quiz_attempts").get() as { n: number }).n;
  return { totalUsers, totalAttempts };
}

export function getDailyTrend(days: number): DailyCounts[] {
  const since = new Date();
  since.setDate(since.getDate() - (days - 1));
  const sinceDate = since.toISOString().slice(0, 10);

  const signupRows = db
    .prepare(
      `SELECT substr(created_at, 1, 10) AS date, COUNT(*) AS n FROM users
       WHERE substr(created_at, 1, 10) >= ? GROUP BY date`
    )
    .all(sinceDate) as { date: string; n: number }[];
  const attemptRows = db
    .prepare(
      `SELECT substr(created_at, 1, 10) AS date, COUNT(*) AS n FROM quiz_attempts
       WHERE substr(created_at, 1, 10) >= ? GROUP BY date`
    )
    .all(sinceDate) as { date: string; n: number }[];

  const signupsByDate = new Map(signupRows.map((r) => [r.date, r.n]));
  const attemptsByDate = new Map(attemptRows.map((r) => [r.date, r.n]));

  const out: DailyCounts[] = [];
  for (let i = 0; i < days; i++) {
    const d = new Date(since);
    d.setDate(d.getDate() + i);
    const date = d.toISOString().slice(0, 10);
    out.push({ date, signups: signupsByDate.get(date) ?? 0, attempts: attemptsByDate.get(date) ?? 0 });
  }
  return out;
}

// ---------------------------------------------------------------------------
// First-run seed — an admin account and a starter question set, so the app
// is usable immediately on a fresh database.
// ---------------------------------------------------------------------------

const DEFAULT_QUESTIONS: Omit<QuizQuestion, "id">[] = [
  {
    order: 1,
    category: "Umumiy ma'lumot",
    text: "Yoshingiz nechida?",
    options: [
      { id: randomUUID(), text: "30 yoshgacha", score: 0 },
      { id: randomUUID(), text: "30–39 yosh", score: 1 },
      { id: randomUUID(), text: "40–49 yosh", score: 2 },
      { id: randomUUID(), text: "50 yosh va undan katta", score: 3 },
    ],
  },
  {
    order: 2,
    category: "Oilaviy tarix",
    text: "Oilangizda (ona, opa-singil, buvi) ko'krak saratoni tarixi bo'lganmi?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Uzoq qarindoshda bo'lgan", score: 1 },
      { id: randomUUID(), text: "Yaqin qarindoshda bo'lgan", score: 3 },
    ],
  },
  {
    order: 3,
    category: "Alomatlar",
    text: "Ko'kragingizda shish yoki tugun sezganmisiz?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 3 },
    ],
  },
  {
    order: 4,
    category: "Alomatlar",
    text: "Ko'krak shakli, o'lchami yoki teri rangida so'nggi paytda o'zgarish kuzatdingizmi?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 2 },
    ],
  },
  {
    order: 5,
    category: "Alomatlar",
    text: "Ko'krak uchidan sut bilan bog'liq bo'lmagan suyuqlik ajralishi bormi?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 2 },
    ],
  },
  {
    order: 6,
    category: "Alomatlar",
    text: "Qo'ltiq ostida shish yoki og'riq sezyapsizmi?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 2 },
    ],
  },
  {
    order: 7,
    category: "Gormonal omillar",
    text: "Uzoq muddat gormonal terapiya yoki kontratseptiv vositalar qabul qilganmisiz?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 1 },
    ],
  },
  {
    order: 8,
    category: "Gormonal omillar",
    text: "Birinchi hayz 12 yoshgacha boshlangan yoki menopauza 55 yoshdan keyin kelganmi?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 1 },
    ],
  },
  {
    order: 9,
    category: "Turmush tarzi",
    text: "Chekasizmi yoki muntazam alkogol iste'mol qilasizmi?",
    options: [
      { id: randomUUID(), text: "Yo'q", score: 0 },
      { id: randomUUID(), text: "Ha", score: 1 },
    ],
  },
  {
    order: 10,
    category: "Turmush tarzi",
    text: "Haftasiga kamida 3 marta jismoniy faollik bilan shug'ullanasizmi?",
    options: [
      { id: randomUUID(), text: "Ha", score: 0 },
      { id: randomUUID(), text: "Yo'q", score: 1 },
    ],
  },
];

// Module-level side effect — runs once per process, but a build tool or a
// burst of cold starts can easily evaluate this module in several processes
// at once, all racing to seed the same empty database. An IMMEDIATE
// transaction takes the write lock before the SELECT even runs, so a second
// racer blocks (via busy_timeout above) until the first one commits, then
// sees the data already there and does nothing — no duplicate rows, no
// UNIQUE-constraint crash.
const seedTransaction = db.transaction(() => {
  const userCount = (db.prepare("SELECT COUNT(*) AS n FROM users").get() as { n: number }).n;
  if (userCount === 0) {
    // ADMIN_EMAIL/ADMIN_PASSWORD (set in .env.local, never committed) let a
    // real deployment seed with its own admin credentials instead of the
    // generic default below.
    createUser({
      email: process.env.ADMIN_EMAIL ?? "admin@mammoai.uz",
      password: process.env.ADMIN_PASSWORD ?? "admin123",
      role: "admin",
      firstName: "Admin",
      lastName: "MammoAI",
      birthDate: "1990-01-01",
      passportSeries: "AA0000000",
    });
  }

  const questionCount = (
    db.prepare("SELECT COUNT(*) AS n FROM quiz_questions").get() as { n: number }
  ).n;
  if (questionCount === 0) {
    for (const q of DEFAULT_QUESTIONS) createQuestion(q);
  }
});

try {
  seedTransaction.immediate();
} catch (err) {
  // A rare last-instant collision (both racers pass busy_timeout within the
  // same tick) can still surface a UNIQUE-constraint error here — safe to
  // ignore, since it only ever means "another process just seeded this".
  if (!(err instanceof Error) || !err.message.includes("UNIQUE constraint")) {
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Settings (key/value)
// ---------------------------------------------------------------------------

export function getSetting(key: string): string | null {
  const row = db.prepare("SELECT value FROM settings WHERE key = ?").get(key) as
    | { value: string | null }
    | undefined;
  return row?.value ?? null;
}

export function setSetting(key: string, value: string | null) {
  db.prepare(
    `INSERT INTO settings (key, value) VALUES (?, ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`
  ).run(key, value);
}

// ---------------------------------------------------------------------------
// Audit log — who (admin/moderator) did what, when. Read-only from the UI.
// ---------------------------------------------------------------------------

export interface AuditLogEntry {
  id: string;
  adminId: string | null;
  adminName: string;
  action: string;
  target: string;
  createdAt: string;
}

export function logAdminAction(adminId: string, adminName: string, action: string, target: string = "") {
  db.prepare("INSERT INTO audit_log (id, admin_id, admin_name, action, target, created_at) VALUES (?, ?, ?, ?, ?, ?)").run(
    randomUUID(),
    adminId,
    adminName,
    action,
    target,
    new Date().toISOString()
  );
}

export function getAuditLog(limit = 200): AuditLogEntry[] {
  const rows = db
    .prepare("SELECT * FROM audit_log ORDER BY created_at DESC LIMIT ?")
    .all(limit) as {
    id: string;
    admin_id: string | null;
    admin_name: string;
    action: string;
    target: string;
    created_at: string;
  }[];
  return rows.map((r) => ({
    id: r.id,
    adminId: r.admin_id,
    adminName: r.admin_name,
    action: r.action,
    target: r.target,
    createdAt: r.created_at,
  }));
}

// ---------------------------------------------------------------------------
// Self-exam calendar (site-side, self-reported — separate from the bot's
// nudge-based monthly reminder, though both point at the same habit)
// ---------------------------------------------------------------------------

export function markSelfExamDone(userId: string, month: string) {
  db.prepare(
    "INSERT INTO self_exam_logs (id, user_id, month, created_at) VALUES (?, ?, ?, ?) ON CONFLICT(user_id, month) DO NOTHING"
  ).run(randomUUID(), userId, month, new Date().toISOString());
}

export function unmarkSelfExamDone(userId: string, month: string) {
  db.prepare("DELETE FROM self_exam_logs WHERE user_id = ? AND month = ?").run(userId, month);
}

export function getSelfExamMonths(userId: string): string[] {
  const rows = db.prepare("SELECT month FROM self_exam_logs WHERE user_id = ?").all(userId) as { month: string }[];
  return rows.map((r) => r.month);
}

// ---------------------------------------------------------------------------
// Family members — lightweight tracked profiles, not full accounts.
// ---------------------------------------------------------------------------

export interface FamilyMember {
  id: string;
  ownerUserId: string;
  firstName: string;
  lastName: string;
  relation: string;
  birthDate: string | null;
  createdAt: string;
}

function rowToFamilyMember(row: {
  id: string;
  owner_user_id: string;
  first_name: string;
  last_name: string;
  relation: string;
  birth_date: string | null;
  created_at: string;
}): FamilyMember {
  return {
    id: row.id,
    ownerUserId: row.owner_user_id,
    firstName: row.first_name,
    lastName: row.last_name,
    relation: row.relation,
    birthDate: row.birth_date,
    createdAt: row.created_at,
  };
}

export function createFamilyMember(input: {
  ownerUserId: string;
  firstName: string;
  lastName?: string;
  relation?: string;
  birthDate?: string | null;
}): FamilyMember {
  const row = {
    id: randomUUID(),
    owner_user_id: input.ownerUserId,
    first_name: input.firstName,
    last_name: input.lastName ?? "",
    relation: input.relation ?? "",
    birth_date: input.birthDate ?? null,
    created_at: new Date().toISOString(),
  };
  db.prepare(
    `INSERT INTO family_members (id, owner_user_id, first_name, last_name, relation, birth_date, created_at)
     VALUES (@id, @owner_user_id, @first_name, @last_name, @relation, @birth_date, @created_at)`
  ).run(row);
  return rowToFamilyMember(row);
}

export function getFamilyMembers(ownerUserId: string): FamilyMember[] {
  const rows = db
    .prepare("SELECT * FROM family_members WHERE owner_user_id = ? ORDER BY created_at ASC")
    .all(ownerUserId) as Parameters<typeof rowToFamilyMember>[0][];
  return rows.map(rowToFamilyMember);
}

export function getFamilyMemberById(id: string): FamilyMember | undefined {
  const row = db.prepare("SELECT * FROM family_members WHERE id = ?").get(id) as
    | Parameters<typeof rowToFamilyMember>[0]
    | undefined;
  return row ? rowToFamilyMember(row) : undefined;
}

export function deleteFamilyMember(id: string, ownerUserId: string) {
  db.prepare("DELETE FROM family_members WHERE id = ? AND owner_user_id = ?").run(id, ownerUserId);
}

/** A family member's attempt history, newest first. */
export function getAttemptsForFamilyMember(familyMemberId: string): QuizAttempt[] {
  const rows = db
    .prepare("SELECT * FROM quiz_attempts WHERE family_member_id = ? ORDER BY created_at DESC")
    .all(familyMemberId) as Parameters<typeof rowToAttempt>[0][];
  return rows.map(rowToAttempt);
}

// ---------------------------------------------------------------------------
// FAQ, clinics, articles — small admin-authored content types, each with an
// optional uz→ru/en translation overlay (FAQ only, same shape as quiz
// question translations); clinics/articles are single-language since
// addresses/phone numbers and long-form text don't machine-translate well
// and are meant to be entered directly in whichever language the admin uses.
// ---------------------------------------------------------------------------

export interface FaqItem {
  id: string;
  order: number;
  question: string;
  answer: string;
  translations?: Partial<Record<"ru" | "en", { question?: string; answer?: string }>>;
}

function rowToFaqItem(row: { id: string; order: number; question: string; answer: string; translations: string | null }): FaqItem {
  return {
    id: row.id,
    order: row.order,
    question: row.question,
    answer: row.answer,
    translations: row.translations ? JSON.parse(row.translations) : undefined,
  };
}

export function getFaqItems(): FaqItem[] {
  const rows = db.prepare('SELECT * FROM faq_items ORDER BY "order" ASC').all() as Parameters<typeof rowToFaqItem>[0][];
  return rows.map(rowToFaqItem);
}

export function createFaqItem(input: Omit<FaqItem, "id">): FaqItem {
  const item: FaqItem = { ...input, id: randomUUID() };
  db.prepare(
    `INSERT INTO faq_items (id, "order", question, answer, translations, created_at) VALUES (@id, @order, @question, @answer, @translations, @createdAt)`
  ).run({
    ...item,
    translations: item.translations ? JSON.stringify(item.translations) : null,
    createdAt: new Date().toISOString(),
  });
  return item;
}

export function updateFaqItem(id: string, input: Omit<FaqItem, "id">): FaqItem {
  const item: FaqItem = { ...input, id };
  db.prepare(
    `UPDATE faq_items SET "order"=@order, question=@question, answer=@answer, translations=@translations WHERE id=@id`
  ).run({ ...item, translations: item.translations ? JSON.stringify(item.translations) : null });
  return item;
}

export function deleteFaqItem(id: string) {
  db.prepare("DELETE FROM faq_items WHERE id = ?").run(id);
}

export interface Clinic {
  id: string;
  order: number;
  name: string;
  address: string;
  phone: string;
  note: string;
}

export function getClinics(): Clinic[] {
  return db.prepare('SELECT id, "order", name, address, phone, note FROM clinics ORDER BY "order" ASC').all() as Clinic[];
}

export function createClinic(input: Omit<Clinic, "id">): Clinic {
  const clinic: Clinic = { ...input, id: randomUUID() };
  db.prepare(
    `INSERT INTO clinics (id, "order", name, address, phone, note, created_at) VALUES (@id, @order, @name, @address, @phone, @note, @createdAt)`
  ).run({ ...clinic, createdAt: new Date().toISOString() });
  return clinic;
}

export function updateClinic(id: string, input: Omit<Clinic, "id">): Clinic {
  const clinic: Clinic = { ...input, id };
  db.prepare(`UPDATE clinics SET "order"=@order, name=@name, address=@address, phone=@phone, note=@note WHERE id=@id`).run(clinic);
  return clinic;
}

export function deleteClinic(id: string) {
  db.prepare("DELETE FROM clinics WHERE id = ?").run(id);
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  published: boolean;
  createdAt: string;
  videoUrl: string;
}

function rowToArticle(row: {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  published: number;
  created_at: string;
  video_url: string | null;
}): Article {
  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    excerpt: row.excerpt,
    content: row.content,
    published: Boolean(row.published),
    createdAt: row.created_at,
    videoUrl: row.video_url ?? "",
  };
}

export function getPublishedArticles(): Article[] {
  const rows = db.prepare("SELECT * FROM articles WHERE published = 1 ORDER BY created_at DESC").all() as Parameters<
    typeof rowToArticle
  >[0][];
  return rows.map(rowToArticle);
}

export function getAllArticles(): Article[] {
  const rows = db.prepare("SELECT * FROM articles ORDER BY created_at DESC").all() as Parameters<typeof rowToArticle>[0][];
  return rows.map(rowToArticle);
}

export function getArticleBySlug(slug: string): Article | undefined {
  const row = db.prepare("SELECT * FROM articles WHERE slug = ?").get(slug) as
    | Parameters<typeof rowToArticle>[0]
    | undefined;
  return row ? rowToArticle(row) : undefined;
}

function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .trim()
      .replace(/['"]/g, "")
      .replace(/[^a-z0-9Ѐ-ӿ]+/g, "-")
      .replace(/^-+|-+$/g, "") || randomUUID().slice(0, 8)
  );
}

export function createArticle(input: {
  title: string;
  excerpt: string;
  content: string;
  published: boolean;
  videoUrl?: string;
}): Article {
  let slug = slugify(input.title);
  if (getArticleBySlug(slug)) slug = `${slug}-${randomUUID().slice(0, 4)}`;
  const article: Article = {
    id: randomUUID(),
    slug,
    title: input.title,
    excerpt: input.excerpt,
    content: input.content,
    published: input.published,
    videoUrl: input.videoUrl ?? "",
    createdAt: new Date().toISOString(),
  };
  db.prepare(
    `INSERT INTO articles (id, slug, title, excerpt, content, published, created_at, video_url) VALUES (@id, @slug, @title, @excerpt, @content, @published, @createdAt, @videoUrl)`
  ).run({ ...article, published: article.published ? 1 : 0 });
  return article;
}

export function updateArticle(
  id: string,
  input: { title: string; excerpt: string; content: string; published: boolean; videoUrl?: string }
): Article {
  const existing = db.prepare("SELECT slug, created_at FROM articles WHERE id = ?").get(id) as
    | { slug: string; created_at: string }
    | undefined;
  if (!existing) throw new ApiError(404, "Maqola topilmadi.");
  db.prepare(
    `UPDATE articles SET title=@title, excerpt=@excerpt, content=@content, published=@published, video_url=@videoUrl WHERE id=@id`
  ).run({
    id,
    title: input.title,
    excerpt: input.excerpt,
    content: input.content,
    published: input.published ? 1 : 0,
    videoUrl: input.videoUrl ?? "",
  });
  return {
    id,
    slug: existing.slug,
    title: input.title,
    excerpt: input.excerpt,
    content: input.content,
    published: input.published,
    videoUrl: input.videoUrl ?? "",
    createdAt: existing.created_at,
  };
}

export function deleteArticle(id: string) {
  db.prepare("DELETE FROM articles WHERE id = ?").run(id);
}

// ---------------------------------------------------------------------------
// Web Push subscriptions
// ---------------------------------------------------------------------------

export function savePushSubscription(userId: string, endpoint: string, p256dh: string, auth: string) {
  db.prepare(
    `INSERT INTO push_subscriptions (id, user_id, endpoint, p256dh, auth, created_at)
     VALUES (?, ?, ?, ?, ?, ?)
     ON CONFLICT(endpoint) DO UPDATE SET user_id = excluded.user_id, p256dh = excluded.p256dh, auth = excluded.auth`
  ).run(randomUUID(), userId, endpoint, p256dh, auth, new Date().toISOString());
}

export function deletePushSubscription(endpoint: string) {
  db.prepare("DELETE FROM push_subscriptions WHERE endpoint = ?").run(endpoint);
}

export function isPushSubscribed(userId: string): boolean {
  const row = db.prepare("SELECT 1 FROM push_subscriptions WHERE user_id = ? LIMIT 1").get(userId);
  return Boolean(row);
}

export default db;
